# Site settings
title:          Yoojung in Seattle
description:    "Seattle Life"
url:            "https://tendtoyj.github.io"

# Author
author:
  name:         Yoojung Kim
  url:          https://www.yoojung.kim
  email:        tendtoyj@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
